-- Enable Row Level Security (RLS)
alter default privileges in schema public grant all on tables to postgres, anon, authenticated, service_role;

-- Vehicles Table
create table public.vehicles (
  vin text not null primary key,
  model text not null, -- 'm3', 'my', 'ms', 'mx', 'ct'
  trim text, -- 'Model 3 Rear-Wheel Drive', etc.
  year integer,
  status text, -- 'new', 'used'
  price numeric,
  currency text default 'EUR',
  paint text,
  wheels text,
  interior text,
  odometer_value numeric,
  odometer_unit text default 'km',
  location_name text,
  city text,
  country_code text,
  url text,
  thumbnail_url text,
  raw_data jsonb, -- Store full original JSON for future proofing
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_seen_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Price History Table
create table public.price_history (
  id bigint generated by default as identity primary key,
  vin text not null references public.vehicles(vin) on delete cascade,
  price numeric not null,
  currency text default 'EUR',
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for faster querying
create index vehicles_model_idx on public.vehicles (model);
create index vehicles_price_idx on public.vehicles (price);
create index vehicles_status_idx on public.vehicles (status);
create index price_history_vin_idx on public.price_history (vin);

-- Trigger to update 'updated_at' column
create or replace function update_modified_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_vehicles_modtime
    before update on public.vehicles
    for each row
    execute procedure update_modified_column();
